version: '3.9'
services:
  ephr:
    container_name: ephr
    image: ephr-image
    environment:
      DB_URL: "host=postgres user=${USERNAME} password=${PASS} database=${DB}"
    depends_on:
      - postgres
    ports:
      - "4000:4000"
  logto:
    container_name: logto
    image: ghcr.io/logto-io/logto:1.0.0-beta.14
    entrypoint: [ "sh", "-c", "sleep 3 && npm run cli db seed -- --swe && npm start" ]
    environment:
      TRUST_PROXY_HEADER: true
      DB_URL: "postgres://${USERNAME}:${PASS}@postgres:5432/logto?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "3001:3001"
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DB}
    ports:
      - "5432:5432"
  dbmate:
    container_name: dbmate
    image: amacneil/dbmate
    entrypoint: ["sh", "-c", "sleep 3 && dbmate up"]
    volumes:
      - "./db:/db"
    environment:
      DATABASE_URL: "postgres://${USERNAME}:${PASS}@postgres:5432/${DB}?sslmode=disable"
    depends_on:
      - postgres
