// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package data

import (
	"time"
)

type Movie struct {
	ID        int64
	CreatedAt time.Time
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
}
