// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64                `json:"id"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	Title     string               `json:"title"`
	Year      int32                `json:"year"`
	Runtime   int32                `json:"runtime"`
	Genres    pgtype.Array[string] `json:"genres"`
	Version   int32                `json:"version"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Token struct {
	Plaintext string             `json:"plaintext"`
	Hash      []byte             `json:"hash"`
	UserID    int64              `json:"user_id"`
	Expiry    pgtype.Timestamptz `json:"expiry"`
	Scope     string             `json:"scope"`
}

type User struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Activated    bool               `json:"activated"`
	Version      int32              `json:"version"`
}

type UsersPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int64 `json:"permission_id"`
}
