// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: movies.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, year, runtime, genres)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, version
`

type CreateMovieParams struct {
	Title   string               `json:"title"`
	Year    int32                `json:"year"`
	Runtime int32                `json:"runtime"`
	Genres  pgtype.Array[string] `json:"genres"`
}

type CreateMovieRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Version   int32              `json:"version"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (CreateMovieRow, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Year,
		arg.Runtime,
		arg.Genres,
	)
	var i CreateMovieRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Version)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE
FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getAllMovies = `-- name: GetAllMovies :many
SELECT id,
       created_at,
       title,
       year,
       runtime,
       genres,
       version
FROM movies
WHERE (to_tsvector('simple', title) @@ plainto_tsquery('simple', $1) OR $1 = '')
  AND (genres @> $2 OR $2 = '{}')
ORDER BY CASE WHEN $3::bool THEN id END,
         CASE WHEN $4::bool THEN id END DESC,
         CASE WHEN $5::bool THEN title END,
         CASE WHEN $6::bool THEN title END DESC,
         CASE WHEN $7::bool THEN year END,
         CASE WHEN $8::bool THEN year END DESC,
         CASE WHEN $9::bool THEN runtime END,
         CASE WHEN $10::bool THEN runtime END DESC
OFFSET $11 LIMIT $12
`

type GetAllMoviesParams struct {
	Title       string               `json:"title"`
	Genres      pgtype.Array[string] `json:"genres"`
	IDAsc       bool                 `json:"id_asc"`
	IDDesc      bool                 `json:"id_desc"`
	TitleAsc    bool                 `json:"title_asc"`
	TitleDesc   bool                 `json:"title_desc"`
	YearAsc     bool                 `json:"year_asc"`
	YearDesc    bool                 `json:"year_desc"`
	RuntimeAsc  bool                 `json:"runtime_asc"`
	RuntimeDesc bool                 `json:"runtime_desc"`
	Offset      int32                `json:"offset_"`
	Limit       int32                `json:"limit_"`
}

func (q *Queries) GetAllMovies(ctx context.Context, arg GetAllMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getAllMovies,
		arg.Title,
		arg.Genres,
		arg.IDAsc,
		arg.IDDesc,
		arg.TitleAsc,
		arg.TitleDesc,
		arg.YearAsc,
		arg.YearDesc,
		arg.RuntimeAsc,
		arg.RuntimeDesc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Title,
			&i.Year,
			&i.Runtime,
			&i.Genres,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovie = `-- name: GetMovie :one
SELECT id, created_at, title, year, runtime, genres, version
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Genres,
		&i.Version,
	)
	return i, err
}

const getMovieCount = `-- name: GetMovieCount :one
SELECT count(*)
FROM movies
`

func (q *Queries) GetMovieCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMovieCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title   = CASE WHEN $1::boolean THEN $2::TEXT ELSE title END,
    year    = CASE WHEN $3::boolean THEN $4::INTEGER ELSE year END,
    runtime = CASE WHEN $5::boolean THEN $6::INTEGER ELSE runtime END,
    genres  = CASE WHEN $7::boolean THEN $8::TEXT[] ELSE genres END,
    version = version + 1
WHERE id = $9
RETURNING title, year, runtime, genres, version
`

type UpdateMovieParams struct {
	UpdateTitle   bool                 `json:"update_title"`
	Title         string               `json:"title"`
	UpdateYear    bool                 `json:"update_year"`
	Year          int32                `json:"year"`
	UpdateRuntime bool                 `json:"update_runtime"`
	Runtime       int32                `json:"runtime"`
	UpdateGenres  bool                 `json:"update_genres"`
	Genres        pgtype.Array[string] `json:"genres"`
	ID            int64                `json:"id"`
}

type UpdateMovieRow struct {
	Title   string               `json:"title"`
	Year    int32                `json:"year"`
	Runtime int32                `json:"runtime"`
	Genres  pgtype.Array[string] `json:"genres"`
	Version int32                `json:"version"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (UpdateMovieRow, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.UpdateTitle,
		arg.Title,
		arg.UpdateYear,
		arg.Year,
		arg.UpdateRuntime,
		arg.Runtime,
		arg.UpdateGenres,
		arg.Genres,
		arg.ID,
	)
	var i UpdateMovieRow
	err := row.Scan(
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Genres,
		&i.Version,
	)
	return i, err
}
