// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: permissions.sql

package data

import (
	"context"
)

const getAllPermissionsForUser = `-- name: GetAllPermissionsForUser :one
SELECT permissions.code
FROM permissions
         INNER JOIN users_permissions ON users_permissions.permission_id = permissions.id
         INNER JOIN users ON users_permissions.user_id = users.id
WHERE users.id = $1
`

func (q *Queries) GetAllPermissionsForUser(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getAllPermissionsForUser, id)
	var code string
	err := row.Scan(&code)
	return code, err
}
