// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: permissions.sql

package data

import (
	"context"
)

const addPermissionsForUser = `-- name: AddPermissionsForUser :many
INSERT INTO users_permissions (user_id, permission_id)
SELECT $1, permissions.id FROM permissions WHERE permissions.code = ANY($2)
RETURNING user_id, permission_id
`

type AddPermissionsForUserParams struct {
	UserID int64
	Code   string
}

func (q *Queries) AddPermissionsForUser(ctx context.Context, arg AddPermissionsForUserParams) ([]UsersPermission, error) {
	rows, err := q.db.Query(ctx, addPermissionsForUser, arg.UserID, arg.Code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersPermission
	for rows.Next() {
		var i UsersPermission
		if err := rows.Scan(&i.UserID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPermissionsForUser = `-- name: GetAllPermissionsForUser :one
SELECT permissions.code
FROM permissions
         INNER JOIN users_permissions ON users_permissions.permission_id = permissions.id
         INNER JOIN users ON users_permissions.user_id = users.id
WHERE users.id = $1
`

func (q *Queries) GetAllPermissionsForUser(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getAllPermissionsForUser, id)
	var code string
	err := row.Scan(&code)
	return code, err
}
