// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Movie struct {
	ID        int64     `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	Title     string    `db:"title" json:"title"`
	Year      int32     `db:"year" json:"year"`
	Runtime   int32     `db:"runtime" json:"runtime"`
	Genres    []string  `db:"genres" json:"genres"`
	Version   int32     `db:"version" json:"version"`
}
